/* Generated file based on ejs templates */
define([], function() {
    return {
    "Constraints.js.ejs": "/*globals define*/\r\n/*jshint node:true, browser:true, camelcase: false*/\r\n\r\n/**\r\n * Generated by ConstraintEvaluator\r\n */\r\n\r\ndefine([], function () {\r\n    'use strict';\r\n\r\n    function Constraints() {\r\n<%constraints.forEach(function (info) {%>\r\n\r\n        this.Constraint_<%=info.safeMetaType%>_<%=info.safeName%> = function () {\r\n\r\n            var fn =\r\n<%=info.script%>;\r\n\r\n            return {\r\n                name: '<%=info.name%>',\r\n                info: '<%=info.info%>',\r\n                metaType: '<%=info.metaType%>',\r\n                fn: fn\r\n            };\r\n        };\r\n<%});%>\r\n    }\r\n\r\n    return Constraints;\r\n});"
}});